[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "https://annotate.codereading.club/:splat"
  status = 301
  force = true

  #[dev]
  #  command = "npm run dev"
  #  port = 3000
